version: '3.9'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:13.4-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - bk-volume:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env
    networks:
      internal-net:

volumes:
  bk-volume:
  bk-gradle-cache:

networks:
  internal-net:
    name: bk-net